name: Deploy Api

on:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - 'Bootstrap-Module/Api/**'

jobs:
  build:
    uses: ./.github/workflows/gradle_build.yml
    with:
      project-name: Api

  push-image:
    needs: build
    uses: ./.github/workflows/ecs_push.yml
    with:
      project-name: Api
      ecr-repository: 677276077921.dkr.ecr.ap-northeast-2.amazonaws.com/ddom/Api
      ecs-cluster: Ddom
      ecs-service: ddom-api
      container-name: api
      docker-file-path: ./Bootstrap-Module/Api/Dockerfile
      task-definition: ddom-api
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-2

