name: Deploy Admin

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
  push:
    branches:
      - main
    paths:
      - 'Bootstrap-Module/Admin/**'

jobs:
  build:
    uses: ./.github/workflows/gradle_build.yml
    with:
      project-name: Admin

  push-image:
    needs: build
    uses: ./.github/workflows/ecs_push.yml
    with:
      project-name: Admin
      ecr-repository: 677276077921.dkr.ecr.ap-northeast-2.amazonaws.com/ddom/admin
      ecs-cluster: Ddom
      ecs-service: ddom-admin
      container-name: admin
      docker-file-path: ./Bootstrap-Module/Admin/Dockerfile
      task-definition: ddom-admin
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-2

