name: Deploy Common

on:
  push:
    branches:
      - main
    paths:
      - '!Bootstrap-Module/**'
      - 'Application-Module/**'
      - 'Common-Module/**'
      - 'Domain-Module/**'
      - 'Infrastructure-Module/**'

jobs:
  deploy-Admin:
    uses: ./.github/workflows/CD-Admin.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-northeast-2

  deploy-Api:
    uses: ./.github/workflows/CD-Api.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-northeast-2

