name: Build Gradle

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
        description: 'The name of the project to build'
    outputs:
      build-success:
        description: "빌드 성공 여부"
        value: ${{ jobs.build.outputs.success }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.build-result.outputs.success }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: gradle setting
        run: |
          chmod +x gradlew

      - name: ${{ inputs.project-name }} build
        id: gradle-build
        continue-on-error: true
        run: ./gradlew build

      - name: Determine build success
        id: build-result
        run: |
          if [ "${{ steps.gradle-build.outcome }}" == "success" ]; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload build artifacts
        if: ${{ inputs.project-name != 'ALL' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.project-name }}-build
          path: ./Bootstrap-Module/${{ inputs.project-name }}/build/libs
